### ISSUE TITLE
Template includes SBST PDF files that may not be needed

### ISSUE THREAD

**Issue by brittag** [18F/federalist-modern-team-template#17]
Over in the cg-landing repository, we have [a directory of SBST PDF files](https://github.com/18F/cg-landing/tree/master/assets/files) left over from when we presumably copied this template, which we hadn't noticed until now. :) This isn't really a problem for us (we'll just delete them from that repo), but it made me realize [the PDF files directory in this template](https://github.com/18F/federalist-modern-team-template/tree/master/assets/files) might be good to delete from here too, if they aren't helpful to the template.

**Comment by wslack** [comment]
Done in https://github.com/18F/federalist-modern-team-template/pull/14
